apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpdesk-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helpdesk-frontend
  template:
    metadata:
      labels:
        app: helpdesk-frontend
    spec:
      containers:
        - name: frontend
          image: helpdesk-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
          env:
            - name: NODE_ENV
              value: "development"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
